name: dops
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # cloud_firestore: ^2.1.0
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.6

  dropdown_search2: ^1.0.2
  email_validator: ^2.0.1
  expendable_fab: ^0.0.3
  file_picker: ^4.2.4
  recase: ^4.0.0
  syncfusion_flutter_datagrid: ^19.3.48
  url_strategy: ^0.2.0
  mask_text_input_formatter: ^2.0.0
  http: ^0.13.4
  get: ^4.3.8
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
