name: dops
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  dropdown_search2: ^1.0.2
  email_validator: ^2.0.1
  expendable_fab: ^0.0.3
  file_picker: ^4.2.4
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.6
  firebase_messaging: ^11.4.0
  flutter:
    sdk: flutter
  get: ^4.6.3
  get_storage: ^2.0.3
  http: ^0.13.4
  mask_text_input_formatter: ^2.0.0
  quick_notify: ^0.2.1
  recase: ^4.0.0
  syncfusion_flutter_datagrid: ^20.1.55
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
