// flutter run -d web-server --web-port 8080 --web-hostname 172.30.134.63

Map<String, List<String>> lists = {
  'Project': [
    'ACE',
  ],
  'Module': [
    'Topside',
    'Flare',
    'Drilling - MDSM',
    'Drilling - DES',
    'Drilling - General',
  ],
  'Level': [
    'Under Deck',
    'Upper Deck',
    'Cellar Deck',
    'Weather Deck',
    'Mezzanine Deck',
    'Valve Access Platform',
    'Common',
    'Load-Out Frame',
    'Section 1',
    'Section 2',
    'Section 3',
    'Section 4',
    'Lower Deck',
    'Pipe Deck',
    'BOP Deck',
    'Drill Floor',
    'Lower Mezz. Deck',
    'Upper Mezz. Deck',
    'Skid Deck',
    'Upper Drill Floor',
    'Living Quarter',
  ],
  'Structure Type': [
    'Access Platform',
    'Handrail',
    'Ladder',
    'Equipment Support',
    'Mechanical Handling',
    'Pipe Support',
    'Primary Beam',
    'Node',
    'Truss',
    'Crane Pedestal',
    'Box Girder',
    'Miscellaneous',
    'Plate Girder Pre-fab',
    'Stabbing Guides',
    'Secondary Steel',
    'Plating',
    'Instrument Support',
    'Manhole',
    'Deck Penetrations',
    'Drain Box',
    'Rodding Hatch',
    'Hatch',
    'Access Hatch',
    'Stair',
    'Tertiary Steel',
    'Life Raft Support',
    'Beam Penetrations',
    'Piperack',
    'Cablerack Support',
    'Cladding',
    'Tank&Vessels',
    'Skid Rail',
    'Standard Drg.',
    'Temporary Steel',
    'Outfitting Steel',
    'Grating'
  ],
  'Status': [
    'Live',
    'Hold',
    'Contains Hold',
  ],
  'Reference Type': [
    'FCN',
    'CCN',
    'SIN',
    'TQ',
    'Design',
  ],
  'System Designation': [
    'Coordinator',
    'User',
  ],
  'Job Title': [
    'Structural Draftsman',
    'Drawing Register Admin',
    'Structural Checker',
    'Structural Designer',
    'Tekla Interface Engineer',
    'Nesting Draftsman',
    'Structural Section Leader',
    'Structural Leading Hand',
  ],
  'Company': [
    'Azfen',
    'Tekfen',
    'Wood',
  ],
  'Employee place': [
    'Office',
    'Home',
    'Left',
  ],
};
