Map<String, List<String>> tableColNames = {
  'reference document': [
    'Project',
    'Rerence Type',
    'Module Name',
    'Document number',
    'Revision code',
    'Title',
    'Transmittal number or received from',
    'Receive date',
    'Action required / Next',
    'Number of assigned documents',
  ],
  'activity': [
    'Activity ID',
    'Activity Name',
    'Module Name',
    'Priority',
    'Coefficient',
    'Current Priority',
    'Budgeted Labor Units',
    'Start Date',
    'Finish Date',
    'Cumulative (%)',
  ],
  'staff': [
    'Badge No',
    'Name',
    'Surname',
    'Patronymic',
    'Full name',
    'Initial (Unique)',
    'System Designation',
    'Job Title',
    'E-mail',
    'Company',
    'Date of Birth',
    'Home Address',
    'Start date',
    'Current place',
    'Contract Finish Date',
    'Contact',
    'Emergency Contact',
    'Emergency Contact Name',
    'Note'
  ],
  'task': [
    'Priority',
    'Activity Code/Title',
    'Azfen Drawing Number',
    'First Sheet Revision',
    'Tekla Phase',
    'Drawing Title',
    'Module',
    'Issue Type',
    'Revision Number',
    'Percentage (%)',
    'Revision Status',
    'Level',
    'Structure Type',
    'Design Drawing',
    'Eng. Change Form No.',
    'Task Create Date',
  ],
};
